### ISSUE TITLE
Undefined array key "guard_name"

### ISSUE THREAD

**Issue by Livijn** [kiritokatklian/nova-permission#26]
When viewing a Role or Permission I get this exception:
> Undefined array key "guard_name" {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key \"guard_name\" at /Users/fredrik/Documents/code/xxx/vendor/spatie/laravel-permission/src/Models/Role.php:73)

The error is coming from the "model"-relation and I can see that the Roles `guard_name` is set: [print screen](https://i.gyazo.com/6c36731d11edf6d49ac6d65ed1afd29d.png)

Also, the `$attributes` is empty when dumping `info("model", [$this->attributes]);` it the `users()`-function on the Role model.

**Comment by kiritokatklian** [comment]
@Livijn I can't seem to be able to reproduce your issue. I logged `$this->attributes` in the Role model and got this:

```log
[2022-10-22 11:10:02] local.INFO: model [{"id":1,"name":"superAdmin","display_name":"Super Administrator","guard_name":"web","created_at":"2021-05-18 23:34:33","updated_at":"2022-04-24 10:59:14"}]
```

I'd reinstall both packages and run `artisan cache:clear` to see if that helps.
Alternatively, you can open an issue over at the main [spatie/laravel-permission](https://github.com/spatie/laravel-permission) repo, because this sounds like an issue caused due to the recent [PR #2219](https://github.com/spatie/laravel-permission/pull/2219).

**Comment by Livijn** [comment]
Removing and then reinstalling the packages actually fixed it. Thanks for your time!
